# Generated by Django 3.1.7 on 2021-03-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'MOBILE'), ('L', 'LAPTOP'), ('SD', 'SERVER_DESKTOPS'), ('TG', 'TECH_GADGETS')], max_length=2),
        ),
    ]
